### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by remicollet** [tecnickcom/tc-lib-barcode#11]
Would be nice if you can have a Changelog this this libraries (and others).

See http://keepachangelog.com/

Yes... I understand this represents some additional work...

**Comment by nicolaasuni** [comment]
Since all the commit history is stored in GIT, you can use "git log" to dynamically generate a changelog. For example:

```
git log --pretty=format:'%C(yellow)%h %Cred%ad %Cblue%an%Cgreen%d %Creset%s' --date=short
```

The command above can be tailored to produce various changelog formats.
