### ISSUE TITLE
s25 barcode seems to be wrong

### ISSUE THREAD

**Issue by kh1978** [tecnickcom/tc-lib-barcode#12]
Hello,
There seems to be problems on s25 barcode encoding: start and stop digit are wrong, and digit 8 has the same encoding as digit 0 :
-> start is '11011010' and should be '1110111010'
-> end is '1101011' and should be '111010111' 
->digit 8 is '10101110111010' and should be '11101010111010'

**Comment by nicolaasuni** [comment]
Thanks for reporting this issue, it has been fixed on the 1.7.2 release.
