### ISSUE TITLE
EAN13 checksum is not public

### ISSUE THREAD

**Issue by remo-moddit** [tecnickcom/tc-lib-barcode#14]
If you create an EAN13 barcode for a 12 digit code, the checksum will be appended and added to the bars. For example, creating an EAN13 barcode for 123456789012 returns actually this barcode: 1234567890128.
Could you make this final code outside accessible, so it can be printed under the barcode or automatically appended on importing 12 digit codes? Currently it is handled in protected methods and variables.

**Comment by nicolaasuni** [comment]
Thank you for your suggestion.
The extended code is now available via getExtendedCode() and it is also returned by getArray().
