### ISSUE TITLE
svg viewBox for IE resizing

### ISSUE THREAD

**Issue by crucifyer** [tecnickcom/tc-lib-barcode#17]
https://github.com/tecnickcom/tc-lib-barcode/blob/develop/src/Type.php
line 325

for IE img tag width

`
$svg = '<?xml version="1.0" standalone="no" ?>'."\n"
    .'<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">'."\n"
    .'<svg width="'.sprintf('%F', ($this->width + $this->padding['L'] + $this->padding['R']))
    .'" height="'.sprintf('%F', ($this->height + $this->padding['T'] + $this->padding['B'])).'"'
    .' version="1.1" xmlns="http://www.w3.org/2000/svg">'."\n"
    ."\t".'<desc>'.htmlspecialchars($this->code, $hflag, 'UTF-8').'</desc>'."\n"
    ."\t".'<g id="bars" fill="'.$this->color_obj->getRgbHexColor().'"'
    .' stroke="none" stroke-width="0" stroke-linecap="square">'."\n";
`
to

`
$width = sprintf('%F', ($this->width + $this->padding['L'] + $this->padding['R']));
$height = sprintf('%F', ($this->height + $this->padding['T'] + $this->padding['B']));
$svg = '<?xml version="1.0" standalone="no" ?>'."\n"
    .'<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">'."\n"
    .'<svg width="'.$width
    .'" height="'.$height.'"'
    .' viewBox="0 0 '.$width.' '.$height.'"'
    .' version="1.1" xmlns="http://www.w3.org/2000/svg">'."\n"
    ."\t".'<desc>'.htmlspecialchars($this->code, $hflag, 'UTF-8').'</desc>'."\n"
    ."\t".'<g id="bars" fill="'.$this->color_obj->getRgbHexColor().'"'
    .' stroke="none" stroke-width="0" stroke-linecap="square">'."\n";
`

thank you.

**Comment by nicolaasuni** [comment]
Fixed in 1.9.2 version.
Thank you for your suggestion.
