### ISSUE TITLE
QRCode issues

### ISSUE THREAD

**Issue by ghispi** [tecnickcom/tc-lib-barcode#19]
It seems that Imagick generated qr codes have some problems due to float values.
Grayish lines appear in the image.
Rounding and casting values to int in \Com\Tecnick\Barcode\Type::getPngDataImagick fixed this for me.

Imagick 3.4.1,
tc-lib-barcode 1.9.2

Example image http://imgur.com/a/OUeUe.
It will be black due to transparency, just save and view in any image viewer.
Also it would be cool to have ability to set background color.

**Comment by nicolaasuni** [comment]
This has been fixed in the 1.10.0 version.
Thank you for reporting this issue.
