### ISSUE TITLE
[FeatureRequest] Background color

### ISSUE THREAD

**Issue by ghispi** [tecnickcom/tc-lib-barcode#20]
All barcodes have transparent background color and there is no way to change that.
It is not issue in code but very big usability issue.

I know that this library originates from tcpdf where usually color of a page is white / one print on white page. But now it became more generic and in mine case I use it to generate QRCODES for web pages and mobile devices where background color can vary and it does not depend on me.

I've already mentioned it in #19 but I think it went unnoticed.

**Comment by nicolaasuni** [comment]
Thank you for your suggestion.
Starting from the version 1.12.1 tc-lib-barcode includes the setBackgroundColor() method.
Please check the new examples and the documentation for further information.
