### ISSUE TITLE
EAN13 Numbers

### ISSUE THREAD

**Issue by dmarklund** [tecnickcom/tc-lib-barcode#25]
Hello!

First, thank you for the excellent work for with this SDK, works very well.
However, I can't seem to get the numbers to be printed along with the barcode for EAN13?

Is this possible with this library?
Something like this is what I have in mind:
http://prntscr.com/e8y0a1

**Comment by sefaYavuz** [comment]
+1

**Comment by ajhar** [comment]
I also have the same question

**Comment by nicolaasuni** [comment]
This library only generates the actual barcode image. It has been designed in this way on purpose.
If you need to add extra text, you can do it separately, choosing you own preferred font, format etc.
If you need a single object (image + text) it is best to work with the SVG format that it is easy to manipulate.
