### ISSUE TITLE
Output original value below the barcode?

### ISSUE THREAD

**Issue by mariordev** [tecnickcom/tc-lib-barcode#27]
This isn't an issue, just a quick question. Is there any way to include the original value in the output barcode? For example, the original value (code) underneath the bars of a linear barcode?

**Comment by nicolaasuni** [comment]
The class is intentionally designed to only output the barcode because the original code or any other element can by added from the parent caller.
My suggestion is to write a wrapper function to decorate the barcode as desired.

**Comment by mariordev** [comment]
Ok great, thanks for getting back to me!
