### ISSUE TITLE
Wrong end of code 128

### ISSUE THREAD

**Issue by Gioggiolo** [tecnickcom/tc-lib-barcode#3]
Hello, first of all thankyou for your work.
I just tried your library, but it looks like there is a problem with the last line of barcode.
This is a generated barcode:
![152152703188_fail](https://cloud.githubusercontent.com/assets/472228/9087506/693d90ac-3b8b-11e5-9368-12c2f4947a9d.png)
but the scanner fails to recognize it.
This is the same generated barcode but I increased the width of last line:
![152152703188_success](https://cloud.githubusercontent.com/assets/472228/9087647/417d8bd4-3b8c-11e5-88c4-9bfdc4886fee.png)
and the scanner recognize it.

The code I used is:

```
require_once('../tc-lib-barcode/vendor/autoload.php');
$barcode = new \Com\Tecnick\Barcode\Barcode();
$obj = $barcode->getBarcodeObj('C128','152152703188',300,50);
$obj->getPng();
```

Thankyou
P.S.
Are you Italian?

**Comment by nicolaasuni** [comment]
Forgot my previous comment.
This is actually a bug in the calculation of the total number of columns in C128 that has been fixed in 1.3.0 version.
