### ISSUE TITLE
Code on barcode doesn't match when using special characters with PDF417

### ISSUE THREAD

**Issue by djbenji92** [tecnickcom/tc-lib-barcode#30]
Hi,
When I generate a PNG barcode PDF417, with the method `getBarcodeObj `, my special character is duplicate. I have confirm it with my smartphone.

For example : 
```
$bobj  = $barcode->getBarcodeObj(
    'PDF417',                         
    'abc/abc',
    -4, 
    -4
)->setBackgroundColor('white');

return $bobj->getPngData();
```
When I scan my barcode, the result doesn't match : "abc//abc"

**Comment by nicolaasuni** [comment]
Fixed in version 1.15.8.
Thanks for reporting this.
