### ISSUE TITLE
What's the model for the QR code generated

### ISSUE THREAD

**Issue by cheoAlejo** [tecnickcom/tc-lib-barcode#31]
Greetings, great library, this is probably a silly question. According to [this link](http://www.qrcode.com/en/codes/model12.html) there are 2 models. What's the model for the QR code generated by this library ?

**Comment by nicolaasuni** [comment]
Actually the QRCode supports 4 correction levels: L, M, Q, H:
http://www.qrcode.com/en/about/error_correction.html
You can specify them when instantiating the class:
https://tcpdf.org/docs/srcdoc/tc-lib-barcode/class-Com.Tecnick.Barcode.Type.Square.QrCode/

**Comment by cheoAlejo** [comment]
Got it. Thanks for the answer.
