### ISSUE TITLE
Support for official USPS font

### ISSUE THREAD

**Issue by aacook** [tecnickcom/tc-lib-barcode#37]
I'm getting some inconsistencies in the IMB bar code generator. Using [an official USPS generator](https://ribbs.usps.gov/4state/flash/barcode.html) (requires Flash), I get the following result for the sequence "0027012345678955555590210" — A full screen grab is below.

![barcode](https://user-images.githubusercontent.com/177171/50739203-dbb9a500-11aa-11e9-93ab-10048f02429d.png)

Using this library and the IMB type, it generates the following bar code which appears to be entirely different:
<img width="546" alt="screenshot 2019-01-06 12 02 18" src="https://user-images.githubusercontent.com/177171/50739228-220f0400-11ab-11e9-9212-330152b22647.png">

I also have some concerns as to whether these bar codes will successfully scan as the USPS [requires a specific font](https://about.usps.com/kits/kit600/4_kit600_steps_creating_002.htm).

Has anyone used these bar codes in a production environment? 

----------

<img width="793" alt="screenshot 2019-01-06 12 00 24" src="https://user-images.githubusercontent.com/177171/50739252-51257580-11ab-11e9-89f2-ac9bb593f074.png">

**Comment by nicolaasuni** [comment]
I am unable to use the USPS onlne generator but I have tested the IMB with the example code from the USPSB3200 specification document (
https://ribbs.usps.gov/intelligentmail_mailpieces/documents/tech_guides/USPSB3200IntelligentMailBarcode4State.pdf ) and I am getting the correct result:
Input string: "01234567094987654321-01234567891"
Output code: "AADTFFDFTDADTAADAATFDTDDAAADDTDTTDAFADADDDTFFFDDTTTADFAAADFTDAADA"
I am going to update the tests and default example to use this code.
