### ISSUE TITLE
Æ,æ,Ø,ø,Å,å danish letters in barcode data

### ISSUE THREAD

**Issue by mladjenigor** [tecnickcom/tc-lib-barcode#39]
Hello,
I'm creating DATA MATRIX barcode, but, when data contain any special chars like danish letters (Æ,æ,Ø,ø,Å,å), created barcode cannot be scanned.

Creating barcode and saving in png file:
`$barcode = new Barcode();`
 `$barcodeObj = $barcode->getBarcodeObj('DATAMATRIX', 'Some string with Æ,æ,Ø,ø,Å,å chars', 150, 150);`
 `$barcodeName = $this->upload->getRandomFileName() . '.png';`
 `$path = $this->upload->getPath($barcodeName, false);`
 `$barcode = $barcodeObj->getGd();`
 `imagepng($barcode, $path);`

Importing png image in pdf using mPdf lib
`$mpdf->Image($path, x, y, w, h);`

**Comment by tasmaniski** [comment]
this PR will fix the issue 
https://github.com/tecnickcom/tc-lib-barcode/pull/40

**Comment by nicolaasuni** [comment]
Unfortunately the PR is breaking existing tests.
Maybe the tests have to be fixed but the PR is incomplete.
