### ISSUE TITLE
is it possible to create/add icon in the centre of QR code

### ISSUE THREAD

**Issue by bewithdhanu** [tecnickcom/tc-lib-barcode#45]
Hi, 
is it possible to create/add icon in the centre of QR code like this image
![image](https://user-images.githubusercontent.com/19368533/64771087-034be300-d56c-11e9-90c1-a354624a1a63.png)

**Comment by nicolaasuni** [comment]
No, the library only produces full QR code but you can output the QR code as SVG and pipe it to another script to add the central logo.
