### ISSUE TITLE
Add getTable method to obtain table based html

### ISSUE THREAD

**Issue by lomby92** [tecnickcom/tc-lib-barcode#46]
I know that already exists getDiv that provide a easy-to-use html code but there is a case where div cannot be used. 
If the library is used to produce HTML for emails it doesn't work. Many email clients are not able to properly display div with padding and borders.
Using a matrix of cells with **table** tag should works.

What you think about this feature?

**Comment by nicolaasuni** [comment]
Unfortunately HTML table do not provide a consistent form of representation.
