### ISSUE TITLE
Visibility Fatal with Init

### ISSUE THREAD

**Issue by ashnazg** [tecnickcom/tc-lib-barcode#52]
Following your [README example](https://github.com/tecnickcom/tc-lib-barcode/blob/develop/README.md#simple-code-example), I'm seeing this error:

`Fatal error: Call to protected Com\Tecnick\Barcode\Type\Square\QrCode\Init::init() 
from context 'Com\Tecnick\Barcode\Type\Square\QrCode' 
in vendor/tecnickcom/tc-lib-barcode/src/Type/Square/QrCode.php on line 217`

Stacktrace:
```
Com\Tecnick\Barcode\Barcode->getBarcodeObj(   )                | ..\index.php:32
Com\Tecnick\Barcode\Type->__construct(   )                     | ..\Barcode.php:122
Com\Tecnick\Barcode\Type\Square\QrCode->setBars(   )           | ..\Type.php:171
Com\Tecnick\Barcode\Type\Square\QrCode->encodeString(   )      | ..\QrCode.php:179
```

v1.15.20 installed via Composer on Windows 10 using PHP 5.3.2.

**Comment by nicolaasuni** [comment]
I am unable to reproduce this issue.
I wonder if it is something Windows-specific?
Which php version are you using?

**Comment by ashnazg** [comment]
`v1.15.20 installed via Composer on Windows 10 using PHP 5.3.2.`

**Comment by nicolaasuni** [comment]
The minimum supported version for tc-lib-barcode is PHP 5.4.0.
