### ISSUE TITLE
[Discussion] GS1 datamatrix support

### ISSUE THREAD

**Issue by Jervelund** [tecnickcom/tc-lib-barcode#56]
I'm looking to implement GS1 support in datamatrix barcodes, which requires adding handling of FNC1, so I'm looking for a brief discussion on what would be the best way to go about this.

From [GS1 DataMatrix - An Introduction and Implementation Guideline](https://www.gs1.dk/media/1211/gs1_datamatrix_guideline.pdf): "The GS1 DataMatrix is formed by adding FNC1 codeword in the first position of Data Matrix ECC 200 version." (page 8) This document also includes a table with codewords, which lists value 232 for FNC1. (page 50)

It's not possible to use the current Datamatrix to add FNC1, as constructing a barcode with chr(232), will encapsulate the char before adding it to the barcode.

My initial thought was to add a check to the datamatrix barcode type for the first char, but that could create issues for users who want to start their barcode with chr(232) as data instead of FNC1.

Would adding a new class for GS1-datamatrix be a better solution? I guess that would only require a small wrapper, that inherits the current datamatrix class and adds the check.

**Comment by nicolaasuni** [comment]
I'll check your PR and see if I can merge things together.

**Comment by Jervelund** [comment]
Thanks.

I'm keen on getting feedback, if you think there's something to improve.

**Comment by nicolaasuni** [comment]
The "Rectangular" and "GS1" Datamatrix features have been implemented in 1.16.0.
Thank you for your suggestion.

**Comment by janfolwarczny** [comment]
Hi 👋

For Datamatrix GS1 mode is currently allowed as the separator only the `FNC1` character (`chr(232)`), but the official **GS1 DataMatrix Guideline** states that the separator character may be also the `<GS>` (`chr(29)`).

https://www.gs1.org/standards/gs1-datamatrix-guideline/25#sub-subsection-02-02-02-title

> The separator character may be FNC1 or the control character (ASCII value 29 (decimal), 1D (hexadecimal)). FNC1 is the character that has the codeword value 232. When either FNC1 or is used as a separator character, the scanner must transfer the character value as control character .

I created a pull-request that adds support also for the chr(29) when DataMatrix is rendered in GS1 mode.
https://github.com/tecnickcom/tc-lib-barcode/pull/91

@nicolaasuni Can you please check the PR and consider merging it?
