### ISSUE TITLE
tc-lib-barcode sometimes error creating barcode

### ISSUE THREAD

**Issue by dirkbore** [tecnickcom/tc-lib-barcode#64]
Hi, i´m using tc-lib-barcode and sometimes it creates errors when creating barcodes. Using code below with firefox browser. one moment it works fine, and at the next moment it don´t works with the same code and same input. Any ideas?

SSL-error log: 

[Wed Jul 14 09:57:09.161085 2021] [php7:error] [pid 225937] [client xxx.xxx.xxx.xxx459] PHP Fatal error:  Uncaught Com\\Tecnick\\Barcode\\Exception: The length of each FNC1-separated code block must be even in /var/www/html/barcodegen/vendor/tecnickcom/tc-lib-barcode/src/Type/Linear/CodeOneTwoEight/Process.php:202\nStack trace:\n#0 /var/www/html/barcodegen/vendor/tecnickcom/tc-lib-barcode/src/Type/Linear/CodeOneTwoEight/CodeOneTwoEightC.php(59): Com\\Tecnick\\Barcode\\Type\\Linear\\CodeOneTwoEight\\Process->getCodeDataC(Array, '1234567')\n#1 /var/www/html/barcodegen/vendor/tecnickcom/tc-lib-barcode/src/Type/Linear/CodeOneTwoEight.php(375): Com\\Tecnick\\Barcode\\Type\\Linear\\CodeOneTwoEight\\CodeOneTwoEightC->getCodeData()\n#2 /var/www/html/barcodegen/vendor/tecnickcom/tc-lib-barcode/src/Type.php(171): Com\\Tecnick\\Barcode\\Type\\Linear\\CodeOneTwoEight->setBars()\n#3 /var/www/html/barcodegen/vendor/tecnickcom/tc-lib-barcode/src/Barcode.php(122): Com\\Tecnick\\Barcode\\Type->__construct('1234567', 650, 220, 'black', Array, Array)\n#4 /var/www/html/barcodegen/index.php(51): Com\\Tecnick\\Barcode\\Barcode->getBarcodeObj('C128C', '1234567', 650, in /var/www/html/barcodegen/vendor/tecnickcom/tc-lib-barcode/src/Type/Linear/CodeOneTwoEight/Process.php on line 202, referer: xxx/index.php

My code:

/* <?php
if (! empty($_POST["generate"])) {
    require ('vendor/autoload.php');
    $barcode = new \Com\Tecnick\Barcode\Barcode();
    $targetPath = "barcode/";
    
    if (! is_dir($targetPath)) {
        mkdir($targetPath, 0777, true);
    }
    $MRP = $_POST["mrp"];
    $productData = "{$MRP}";
    $barcode = new \Com\Tecnick\Barcode\Barcode();
    $bobj = $barcode->getBarcodeObj('C128C', "{$productData}", 650, 220, 'black', array(0, 0, 0, 0));
    
    
    $imageData = $bobj->getPngData();
    $timestamp = time();
    
    file_put_contents($targetPath . $timestamp . '.png', $imageData);
    ?> */

**Comment by nicolaasuni** [comment]
I am unable to reproduce this.
Will you be able to provide the static input that generates the error?

**Comment by nicolaasuni** [comment]
Closing this for lack of feedback.
