### ISSUE TITLE
Wrong PDF417 barcode for Croatian letters (čćšđž)

### ISSUE THREAD

**Issue by zkalinic71** [tecnickcom/tc-lib-barcode#65]
Hi,

when I create PDF417 barcode with getBarcodeObj('PDF417','Test for čćđšž') I get a barcode, which, scanned by barcode scanner, scans this: Test for ÄÄÄÅ¡Å¾

![PDF417](https://user-images.githubusercontent.com/93569251/139793012-72d85760-7e9f-4e6a-99a1-764e4adc8f59.PNG)

**Comment by nicolaasuni** [comment]
This works for me.
Try with a scanner that support UTF8
