### ISSUE TITLE
EDIFACT encoding doesn't work correctly

### ISSUE THREAD

**Issue by Xclynaj** [tecnickcom/tc-lib-barcode#67]
Hi. EDIFACT encoding doesn't work correctly:

`-=-1-=-2-=-3xyz` =>` -=-1-=-2-=-3^W); \AW[)> 06 03`
`-=-1-=-2-=-3-xy` =>` -=-1-=-2-=-3xy`

`<?php
require ('vendor/autoload.php');
$barcode = new \Com\Tecnick\Barcode\Barcode();
echo "<style>body{margin: 50}</style>";
echo "<p>-=-1-=-2-=-3xyz</p>";
$bobj = $barcode->getBarcodeObj('DATAMATRIX', '-=-1-=-2-=-3xyz', -4, -4);
echo $bobj->getHtmlDiv();
echo "<br /><br /><br />";
echo "<p>-=-1-=-2-=-3-xy</p>";
$bobj = $barcode->getBarcodeObj('DATAMATRIX', '-=-1-=-2-=-3-xy', -4, -4);
echo $bobj->getHtmlDiv();`

I propose a [solution](https://github.com/tecnickcom/tc-lib-barcode/pull/66)

**Comment by nicolaasuni** [comment]
Thank you for your PR, it has been merged in 1.17.7.
