### ISSUE TITLE
Encoding of datamatrix

### ISSUE THREAD

**Issue by flaviencrochard** [tecnickcom/tc-lib-barcode#74]
Hello,
default encoding (ASCII) seems to be hard coded in method getHighLevelEncoding : could the params be used to set the desired encoding ?
I managed to fork and patch but i'm not proud of that (my case is to use C40 as default encoding)
Thanks for your help if it's possible.

**Comment by nicolaasuni** [comment]
If you share your code maybe I can have a look.

**Comment by tiktaz** [comment]
@flaviencrochard I have the same problem, can you share your code please ? :)

**Comment by flaviencrochard** [comment]
Hello,
Sure, here is my code :

```
$data = "IS010000000000000000000000S1173082622170111S21.2.250.1.213.1.4.8\x1DS3JEAN-MICHEL\x1DS4INS-FAMILLE-UN\x1DS5MS607-08-1973S726221";

$datamatrix = (new Barcode())->getBarcodeObj(
                'DATAMATRIX',
                $data,
                72,
                72
            )->getPngData(false);
```


I didn't see any option to set C40 encoding.

Thanks a lot

**Comment by nicolaasuni** [comment]
When selecting the barcode type you can add some comma-separated parameters.
For example ('DATAMATRIX,R,GS1') as in:
https://github.com/tecnickcom/tc-lib-barcode/blob/main/example/index.php#L66

The encoding is currently selected automatically.
A single barcode can contain multiple encodings depending on the data.
