### ISSUE TITLE
Aztec codes

### ISSUE THREAD

**Issue by gbsystems** [tecnickcom/tc-lib-barcode#76]
### Aztec codes ?
Can this excellent package be further enhanced to produce 2D Aztec codes ?

**Comment by atorralb** [comment]
damn, that sounds interesting... do you have a reference?

**Comment by mjohndus** [comment]
Works fine with Aztec a Metzli-fork [extended Samples](https://mjohndus.github.io/) - **not ready**.

**Comment by nicolaasuni** [comment]
Do you have a fork/branch you are working on this?

**Comment by mjohndus** [comment]
only hobby (at the moment no time) -> here is my fork:  [Aztec](https://github.com/mjohndus/tc-lib-barcode)

**Comment by nicolaasuni** [comment]
@mjohndus Would you please open a PR when it is ready? (it must include unit tests).

**Comment by nicolaasuni** [comment]
ATZEC Code encoder was added at:
https://github.com/tecnickcom/tc-lib-barcode/pull/79
There are probably some minor fixes due to corner cases but it seems working fine.
