### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mplusdaya** [tecnickcom/tc-lib-barcode#81]
A PHP Error was encountered
Severity: Warning

Message: Uninitialized string offset 19

Filename: CodeOneTwoEight/Process.php

Line Number: 208

Backtrace:

File: /home/parasmstaging/public_html/bhusawal-plant/vendor/tecnickcom/tc-lib-barcode/src/Type/Linear/CodeOneTwoEight/Process.php
Line: 208
Function: _error_handler

File: /home/parasmstaging/public_html/bhusawal-plant/vendor/tecnickcom/tc-lib-barcode/src/Type/Linear/CodeOneTwoEight/CodeOneTwoEightC.php
Line: 59
Function: getCodeDataC

File: /home/parasmstaging/public_html/bhusawal-plant/vendor/tecnickcom/tc-lib-barcode/src/Type/Linear/CodeOneTwoEight.php
Line: 375
Function: getCodeData

File: /home/parasmstaging/public_html/bhusawal-plant/vendor/tecnickcom/tc-lib-barcode/src/Type.php
Line: 171
Function: setBars

File: /home/parasmstaging/public_html/bhusawal-plant/vendor/tecnickcom/tc-lib-barcode/src/Barcode.php
Line: 122
Function: __construct

File: /home/parasmstaging/public_html/bhusawal-plant/application/models/admin/dashboard/gatepass/Md_gatepass.php
Line: 80
Function: getBarcodeObj

File: /home/parasmstaging/public_html/bhusawal-plant/application/controllers/admin/dashboard/gatepass/Cn_gatepass.php
Line: 257
Function: set_barcode

File: /home/parasmstaging/public_html/bhusawal-plant/index.php
Line: 315
Function: require_once

Getting this error 

PHP 8.1

OS Ubuntu 20 on webmin

this was working earlier

Additional Info: used C128C : CODE 128 C for barcode generation

**Comment by nicolaasuni** [comment]
The line 208:
https://github.com/tecnickcom/tc-lib-barcode/blob/main/src/Type/Linear/CodeOneTwoEight/Process.php#L208
Is just an assignment, so you are probably using an old version and need to upgrade?
