### ISSUE TITLE
can i use it  without composer?

### ISSUE THREAD

**Issue by snmoney** [tecnickcom/tc-lib-barcode#83]
i want to setup barcode feature on an old device with a old version of PHP ( like 5.6.x ), and for some reasons i can not upgrade or install composer.

it's there any way to use without composer autoload, or any other project as replacement.

**Comment by nicolaasuni** [comment]
tc-lib-barcode now requires PHP >= 8.0.
Note : https://www.php.net/supported-versions.php
PHP versions less than 8.1 are no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities.
