### ISSUE TITLE
Datamatrix-encoding of special character

### ISSUE THREAD

**Issue by knallcharge** [tecnickcom/tc-lib-barcode#85]
I'm trying to encode the special "trademark"-character (™) into a datamatrix code.
The character has the ASCII-number 226 so it is within the ASCII specification for datamatrix (1-255).

The generated datamatrix-code looks like this:

![grafik](https://github.com/user-attachments/assets/f982bfd4-c0af-424c-8f64-0e5d40107f9a)

Which, when decoded just gives weird characters, depending on the decoder sometimes several chars sometimes just a question mark.

No I'm confused whether this is some kind of multibyte (?) problem or if the character is just not supported (even though within the allowed range).
I have tried online encoders and received conflicting results, e.g. this generator (https://products.aspose.app/barcode/de/generate) will encode and decode the character correctly while a different decoder will also show weird characters when decoding the image generated with this encoder. Different encoders like this one (https://barcode.tec-it.com/de/DataMatrix) will not encode the character at all but display an error message that invalid characters have been entered.

So my question is: Is ™ supported at all (according to the specs it should) and what do I need to do to generate it correctly? e.g. use/convert to a different character set?
Also: Would it be possible to throw an execption in datamatrx if characters that are not supported are trying to be generated? (Like it is already done with C128: If I try to encode the trademark-sign here, I receive the message "Error: Invalid character sequence: 226")

**Comment by nicolaasuni** [comment]
The ASCII character 153 (trademark symbol) is not supported by Text encoding modes.
You can check the supported ASCII characters for Text modes at:
https://en.wikipedia.org/wiki/Data_Matrix

However, the character can still be encoded in binary but your decoder has to know how to convert it.

**Comment by knallcharge** [comment]
Ok, thanks for the clarification! 👍
