### ISSUE TITLE
Allow generating inline SVG code

### ISSUE THREAD

**Issue by MatTheCat** [tecnickcom/tc-lib-barcode#88]
`Type::getSvgCode` returns a DTD ([which is discouraged](https://jwatt.org/svg/authoring/#doctype-declaration)) and an XML declaration which are fine for a standalone files, but not for inlining.

Changing `Type::getSvgCode` signature to `public function getSvgCode(bool $xmlDeclaration = true, bool $dtd = true): string` would keep BC and allow to generate SVG code for all use-cases.

**Comment by nicolaasuni** [comment]
@MatTheCat Thank you for this suggestion.
In the tc-lib-barcode version 2.4.0 I have added a new method getInlineSvgCode() that only returns the <svg> tag.
The existing method getSvgCode() now returns the extra xml header, the DOCTYPE has been removed and the svg version has been set to version 1.2.
Hopefully this will cover the reported use-cases.
